server:
  port: 8080

spring:
  application:
    name: weather-intel-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/weather_intel
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: weather-intel-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB

app:
  ai-service:
    url: http://localhost:8001
  kafka:
    topic: weather.raw.ingestion
    fallback-in-memory: true
  storage:
    upload-dir: uploads
